# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='number_of_books',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='number_of_books',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
