# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20170315_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publisher',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
