# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170315_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='view_count',
        ),
    ]
